app/__init__.py
from flask import Flask
from app.views import main


def create_app(debug=False):
    app = Flask(__name__)
    app.debug = debug

    app.register_blueprint(main)

    return app

app/controllers.py
from flask import render_template, session
from app.mongo import News, Menu
import bcrypt
import time

class HomeController:

	def update_featured(self, data):
		code = data.get('data[code]')
		News.mongo(self.database).update_many({},{"$set":{'featured': 'off'}})
		time.sleep(1)
		News.mongo(self.database).update_one({'slug':code}, {"$set":{'featured': 'on'}})
	
	def make_comment(self, code, data):
		News.mongo(self.database).update({'slug' : code}, { "$push" : {'comments': {'comment' : data.get('comment')} }})

	def detail(self, code):
		current = None
		n = News.mongo(self.database).find({'slug':code})
		if n:
			current = list(n)[0]
		return render_template('detail.html', current=current, placeholder='Noticias, jugadores, torneos, etc.')

	def view(self, query):
		search = query.get('query',False)

		list_menu = Menu.getAll(self.database, False)
		News.mongo(self.database).create_index([('description', 'text')])
		featured_new = News.mongo(self.database).find_one({'featured':'on'})
		if search:
			news = list(News.mongo(self.database).find({"$text": { "$search": search }}))
		else:
			news = list(News.getAll(self.database, True,{"featured":"off"}))

		return render_template('index.html',list_menu=list_menu,featured_new=featured_new, news = news,
			placeholder='Noticias, jugadores, torneos, etc.')

class AdminController:

	def attempt(self, username, password):
		pswd = bcrypt.hashpw(bytes(password.encode('utf-8')), bcrypt.gensalt())
		us= self.database.db.users.find_one({"username":username})
		if us:
			if bcrypt.checkpw(password.encode('utf-8'), us['password']):
				return { 'status':True, 'message':'ok'}
			else:
				return { 'status':False, 'message':'invalid password'}
		else:
			{ 'status':False, 'message':'User doesnt exist'}

	def register(self, username, password):
		pswd = bcrypt.hashpw(bytes(password.encode('utf-8')), bcrypt.gensalt())
		return self.database.db.users.insert({"username":username, "password":pswd})

	def login(self):
		return render_template('admin/index.html',
			news = list(News.getAll(self.database)),
			placeholder='Noticias, jugadores, torneos, etc.')

	def dashboard(self):
		return render_template('admin/dashboard.html')

class NewsController:

	def edit_view(self, code):
		current = None
		return render_template('admin/news/add_edit.html', current=code)
	
	def save_item(self, data):
		n = News.form(data)
		n.save(self.database)
		return render_template('admin/news/add_edit.html')

	def add_view(self):
		model = News.form()
		return render_template('admin/news/add_edit.html', model=model)

	def view(self):
		news = list(News.getAll(self.database))
		return render_template('admin/news/list.html', news=news)

class ContentController:

	def add_menu(self, data):
		m = Menu()
		m.name = data.get('name')
		m.url = data.get('url')
		m.save(self.database)
		return {'status' : True}
	def view(self):
		list_menu = Menu.getAll(self.database)
		return render_template('admin/content/index.html', list_menu = list(list_menu) )

app/views.py
from flask import Blueprint, jsonify, request, redirect, url_for, session
import bcrypt
from app.app_context import home_controller, admin_controller, news_controller, content_controller
from app.mongo import MongoConnection

main = Blueprint('main', __name__)


db_mongo = MongoConnection()

# TODO this does not work
@main.route('/', methods=['GET'])
def home():
	home_controller.database = db_mongo
	return home_controller.view(request.args)
 

@main.route('/detail/<code>', methods=['GET'])
def detail_news(code): 
	home_controller.database = db_mongo
	return home_controller.detail(code)

@main.route('/make-comment/<code>', methods=['POST'])
def make_comment(code):
	home_controller.database = db_mongo
	home_controller.make_comment(code, request.form)
	return redirect( url_for('main.detail_news', code=code) )

@main.route('/status/featured', methods=['POST'])
def featured_status():
	home_controller.database = db_mongo
	home_controller.update_featured(request.form)
	return ''

@main.route('/admin', methods=['GET', 'POST'])
def admin():
	admin_controller.database = db_mongo

	if request.method == 'POST':
		username = request.form.get('username')
		password = request.form.get('password')
		access = admin_controller.attempt( username, password )
		if access['status']:
			session['user'] = access
			return redirect( url_for('main.dashboard') )
		else:
			print('not')

	if 'user' in session:
		return redirect( url_for('main.dashboard') )
	return admin_controller.login()


@main.route('/admin/dashboard', methods=['GET', 'POST'])
def dashboard(): 
	return admin_controller.dashboard()

@main.route('/admin/news', methods=['GET', 'POST'])
def news(): 
	news_controller.database = db_mongo
	return news_controller.view()
@main.route('/admin/content')
def content():
	content_controller.database = db_mongo
	return content_controller.view()
	
@main.route('/admin/content/add-menu', methods=['POST'])
def add_menu():
	content_controller.database = db_mongo
	content_controller.add_menu(request.form)
	return redirect( url_for('main.content') )

@main.route('/admin/news/add', methods=['GET' ,'POST'])
def add_news():
	news_controller.database = db_mongo
	if request.method == 'POST':
		news_controller.save_item(request.form)
		return redirect( url_for('main.news') )

	return news_controller.add_view()

@main.route('/admin/news/edit/<code>', methods=['GET' ,'POST'])
def edit_news(code):
	news_controller.database = db_mongo
	return news_controller.edit_view(code)

app/templates/_app.html
<!doctype html>
<html>
<head>
  <title>{% block title %}{% endblock %} - Ajedrez</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
</head>
<body>

<section class="content">
  <header style="background-image:url('{{ url_for('static', filename='images/bg.jpg') }}') ">
    <div class='wrapper'>
      <div class='brand'>
      <div class='logo'
       style="background-image:url('{{ url_for('static', filename='images/logo.jpg') }}') "><a href="{{url_for('main.home')}}">pagina principal</a></div>
     </div>
      <div class='searcher'>
          <form action='/'>
           <div class='f-search'>
            
              <input type="text" placeholder='{{placeholder}}'
                autocomplete="off" 
                 class='control' name="query" />
              <button class='btn'><i class='fa fa-search'></i></button>

          </div>
          </form>

      </div>
    </div>
  </header>
  <div class='topbar'>
    <div class='wrapper'>
      <div class='menu'>
          <ul>
            {% for x in list_menu%}
            <li><a href="{{x.url}}">{{x.name}}</a></li>
            {% endfor%}
          </ul>
      </div>
    </div>
  </div>
  {% block content %}{% endblock %}
</section>
<div class='footer'>
  <footer>
    <div class='wrapper'>
      <div class='menu-cols'>
        <div class='item-menu-cols'>
          <a href="{{url_for('main.home')}}" class="logo-footer">
                      <i class='fa fa-chess'></i>
                          KING CHESS
                    </a>
        </div>
      </div>
    </div>
  </footer>
</div>
<script type="text/javascript" src="{{ url_for('static', filename='js/msry.js') }}"></script>

</body>
</html>

app/templates/_blank.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1>Flaskr</h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

app/templates/detail.html
{% extends '_app.html' %}
{% block content %}

  <div class='main'>
  	<div class='wrapper'>
  		<div class='news-detail'>
	  		<h2>{{current['title']}}</h2>
	  		<div class='text'>{{current['description']|safe}}</div>
  		</div>
  		
  		<div class='comments'>
  			<div class='comment-section'>
  				<form id='form-comment' action='{{url_for("main.make_comment",code=current['slug'])}}' method='POST'>
	  				<textarea class='control comment' id='tfComment' name='comment'></textarea>
	  				<div id='response-message' class='text-error'></div>
	  				<button type='submit' class='btn btn-comment'>Enviar comentario</button>
  				</form>
  			</div>
  			<div class='list-comment'>
					{% for comment in current['comments'] %}

					<div class='comment-item'>
						<div class='image'><img width='70' src='/static/images/avatar.png' /></div>
						<div class='text'>
							{{comment['comment']}}
						</div>
					</div>


				{% endfor %}
			</div>
  		</div>
  	</div>
  </div>

{% endblock %}

app/templates/index.html
{% extends '_app.html' %}
{% block content %}

  <div class='main'>
  	<div class='wrapper'>
  		{% if not request.args.get('query', False) %}
	  		<div class='main-news'>
	  			<div class='featured'>
	  				
	  				<div class='image' 
		  					style="background-image:url(http://lorempixel.com/420/420/cats/{{ range(1, 5) | random }}) ">
			  					<div class='content'>
					  					<h3>
				  						<a href='{{ url_for("main.detail_news", code=featured_new.slug) }}'>
						  					{{featured_new.title}}
						  				</a>
						  				</h3>
					  					<p>{{featured_new.description|cleanhtml|summary}}</p>
			  					</div>
		  				</div>
	  			</div>
	  			<div class='related-news'>
	  				<div class='item-related'></div>
	  			</div>
	  		</div>
  		{%endif%}
  		<div class='news'>
  			{% if  request.args.get('query', False) %}
  				<h3 class='title-result'>Resultado de búsqueda: {{request.args.get('query', False) }}</h3>
  			{% endif %}
  			<div id="grid" data-columns>
  				{% for item in news %}
	  			<div class='item'>
	  				<div class='meta-image'
	  					style="background-image:url(http://lorempixel.com/320/120/cats/{{ range(1, 5) | random }}) ">
	  				</div>
	  				<div class='meta-info'>
	  					<h3><a href='{{ url_for("main.detail_news", code=item.slug) }}'>{{item.title}}</a></h3>
	  					<p>{{item.description|cleanhtml|summary}}</p>
	  				</div>
	  			</div>
	  			{% endfor %}
  			</div>
  		</div>
  	</div>
  </div>

{% endblock %}